import type { Localized } from './types';

/**
 * Interface strings (buttons, labels, screen-reader texts) – not page content.
 */
export const ui = {
  skipToContent: { de: 'Zum Inhalt springen', en: 'Skip to content' },
  mainNav: { de: 'Hauptnavigation', en: 'Main navigation' },
  footerNav: { de: 'Fußzeilen-Navigation', en: 'Footer navigation' },
  openMenu: { de: 'Menü öffnen', en: 'Open menu' },
  closeMenu: { de: 'Menü schließen', en: 'Close menu' },
  home: { de: 'Startseite', en: 'Home page' },
  language: { de: 'Sprache', en: 'Language' },
  switchToDark: { de: 'Dunkles Design aktivieren', en: 'Switch to dark mode' },
  switchToLight: { de: 'Helles Design aktivieren', en: 'Switch to light mode' },
  learnMore: { de: 'Mehr erfahren', en: 'Learn more' },
  allCourses: { de: 'Alle Kurse ansehen', en: 'See all classes' },
  toSchedule: { de: 'Zum Stundenplan', en: 'View timetable' },
  ageGroup: { de: 'Alter', en: 'Age' },
  filterBy: { de: 'Filtern nach Zielgruppe', en: 'Filter by audience' },
  all: { de: 'Alle', en: 'All' },
  time: { de: 'Zeit', en: 'Time' },
  course: { de: 'Kurs', en: 'Class' },
  level: { de: 'Stufe', en: 'Level' },
  teacher: { de: 'Lehrkraft', en: 'Teacher' },
  noEntries: { de: 'Keine Kurse für diese Auswahl.', en: 'No classes for this selection.' },
  upcomingEvents: { de: 'Kommende Termine', en: 'Upcoming' },
  pastEvents: { de: 'Vergangene Termine', en: 'Past events' },
  noUpcoming: { de: 'Aktuell sind keine Termine geplant.', en: 'No events scheduled at the moment.' },
  teaches: { de: 'Unterrichtet', en: 'Teaches' },
  address: { de: 'Adresse', en: 'Address' },
  phone: { de: 'Telefon', en: 'Phone' },
  email: { de: 'E-Mail', en: 'Email' },
  openingHours: { de: 'Bürozeiten', en: 'Office hours' },
  openMap: { de: 'Karte öffnen (OpenStreetMap)', en: 'Open map (OpenStreetMap)' },
  opensInNewTab: { de: '(öffnet in neuem Tab)', en: '(opens in new tab)' },
  placeholderBadge: { de: 'Beispielinhalt', en: 'Sample content' },
  notFoundTitle: { de: 'Seite nicht gefunden', en: 'Page not found' },
  notFoundText: {
    de: 'Diese Seite gibt es leider nicht (mehr).',
    en: "Sorry, this page doesn't exist (anymore).",
  },
  backHome: { de: 'Zur Startseite', en: 'Back to home' },
  weekdays: {
    mon: { de: 'Montag', en: 'Monday' },
    tue: { de: 'Dienstag', en: 'Tuesday' },
    wed: { de: 'Mittwoch', en: 'Wednesday' },
    thu: { de: 'Donnerstag', en: 'Thursday' },
    fri: { de: 'Freitag', en: 'Friday' },
    sat: { de: 'Samstag', en: 'Saturday' },
    sun: { de: 'Sonntag', en: 'Sunday' },
  },
  audiences: {
    kids: { de: 'Kinder', en: 'Children' },
    teens: { de: 'Jugendliche', en: 'Teens' },
    adults: { de: 'Erwachsene', en: 'Adults' },
    family: { de: 'Eltern & Kind', en: 'Parent & child' },
  },
  copyright: { de: 'Alle Rechte vorbehalten.', en: 'All rights reserved.' },
} satisfies Record<string, Localized | Record<string, Localized>>;
