#!/usr/bin/env node
/**
 * Git-based ticket board. Tickets are Markdown files in tickets/ with a small front-matter header;
 * BOARD.md is generated from them.
 *
 *   yarn ticket:new "Add lightbox to gallery" [--type feat|fix|chore|docs] [--priority high|medium|low]
 *   yarn ticket:move 12 in-progress           (backlog | todo | in-progress | review | done)
 *   yarn board                                 regenerate BOARD.md
 */
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const STATUSES = ['backlog', 'todo', 'in-progress', 'review', 'done'];
const TITLES = { backlog: '🗂 Backlog', todo: '📋 To do', 'in-progress': '🚧 In progress', review: '👀 Review', done: '✅ Done' };
const root = new URL('..', import.meta.url).pathname;
const dir = join(root, 'tickets');

function parse(file) {
  const text = readFileSync(join(dir, file), 'utf8');
  const m = text.match(/^---\n([\s\S]*?)\n---/);
  if (!m) return null;
  const meta = Object.fromEntries(
    m[1].split('\n').map((l) => {
      const i = l.indexOf(':');
      return [l.slice(0, i).trim(), l.slice(i + 1).trim().replace(/^"|"$/g, '')];
    }),
  );
  return { ...meta, id: Number(meta.id), file, text };
}

function all() {
  return readdirSync(dir)
    .filter((f) => /^\d+-.*\.md$/.test(f))
    .map(parse)
    .filter(Boolean)
    .sort((a, b) => a.id - b.id);
}

const slugify = (s) =>
  s
    .toLowerCase()
    .replace(/ä/g, 'ae').replace(/ö/g, 'oe').replace(/ü/g, 'ue').replace(/ß/g, 'ss')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')
    .slice(0, 40)
    .replace(/-$/, '');

function board() {
  const tickets = all();
  let md = `# Ticket board\n\n> Generated by \`yarn board\` from the files in [tickets/](tickets/). Do not edit by hand.\n> Workflow: see [CONTRIBUTING.md](CONTRIBUTING.md#tickets).\n\n`;
  md += `| Status | Count |\n|---|---|\n${STATUSES.map((s) => `| ${TITLES[s]} | ${tickets.filter((t) => t.status === s).length} |`).join('\n')}\n\n`;
  for (const s of STATUSES) {
    const list = tickets.filter((t) => t.status === s);
    md += `## ${TITLES[s]}\n\n`;
    if (list.length === 0) {
      md += '_empty_\n\n';
      continue;
    }
    md += '| # | Type | Title | Priority | Branch |\n|---|---|---|---|---|\n';
    for (const t of list) {
      md += `| [#${t.id}](tickets/${t.file}) | ${t.type} | ${t.title} | ${t.priority} | \`${t.type}/${t.id}-${slugify(t.title)}\` |\n`;
    }
    md += '\n';
  }
  writeFileSync(join(root, 'BOARD.md'), md);
  console.log(`✓ BOARD.md updated (${tickets.length} tickets)`);
}

function flag(name, fallback) {
  const i = process.argv.indexOf(`--${name}`);
  return i > -1 ? process.argv[i + 1] : fallback;
}

const [cmd, ...rest] = process.argv.slice(2);

if (cmd === 'new') {
  const title = rest.filter((a, i) => !a.startsWith('--') && !(rest[i - 1] ?? '').startsWith('--')).join(' ');
  if (!title) {
    console.error('Usage: yarn ticket:new "Title" [--type feat] [--priority medium]');
    process.exit(1);
  }
  const type = flag('type', 'feat');
  const priority = flag('priority', 'medium');
  const id = Math.max(0, ...all().map((t) => t.id)) + 1;
  const slug = slugify(title);
  const file = `${String(id).padStart(3, '0')}-${slug}.md`;
  const today = new Date().toISOString().slice(0, 10);
  writeFileSync(
    join(dir, file),
    `---\nid: ${id}\ntitle: "${title}"\ntype: ${type}\nstatus: backlog\npriority: ${priority}\ncreated: ${today}\n---\n\n## Goal\n\n_What should be possible afterwards?_\n\n## Acceptance criteria\n\n- [ ] …\n\n## Notes\n\nBranch: \`${type}/${id}-${slug}\` · Commits: \`${type}(#${id}): …\`\n`,
  );
  console.log(`✓ Created tickets/${file}`);
  console.log(`  Branch:  git switch dev && git switch -c ${type}/${id}-${slug}`);
  board();
} else if (cmd === 'move') {
  const [idArg, status] = rest;
  if (!STATUSES.includes(status)) {
    console.error(`Status must be one of: ${STATUSES.join(', ')}`);
    process.exit(1);
  }
  const t = all().find((x) => x.id === Number(idArg));
  if (!t) {
    console.error(`Ticket #${idArg} not found`);
    process.exit(1);
  }
  writeFileSync(join(dir, t.file), t.text.replace(/^status:.*$/m, `status: ${status}`));
  console.log(`✓ #${t.id} → ${status}`);
  board();
} else if (cmd === 'board') {
  board();
} else {
  console.error('Commands: new | move | board');
  process.exit(1);
}
